#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
#mybatis.type-aliases-package=com.it.usercenter.mybatis.entity
mybatis:
  type-aliases-package: com.it.usercenter.mybatis.entity
  mapper-locations: classpath:mappers/*xml
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/universe
    username: root
    password: 123456
    # session 失效时间
  session:
    timeout: 86400

